version: '3'

services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./bin/sql/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - db-data:/var/lib/postgresql/data
    networks: 
      local:
        aliases:
          - postgres

  exchange:
    build:
      context: app
    restart: always
    env_file: .env
    links:
      - postgres:postgres
    networks:
      local:
        aliases:
          - exchange
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules

networks: 
  local:
    
volumes:
  db-data: